---
jobs:
- name: build-test
  public: true
  serial: true
  plan:
  - get: source-code
  - task: build
    file: source-code/concourse/build.yml

- name: deploy
  public: true
  serial: true
  plan:
  - get: source-code
    passed: [build-test]
  - task: deploy
    params:
        AWS_ACCESS_KEY_ID: ((access-key))
        AWS_SECRET_ACCESS_KEY: ((secret-key))
    file: source-code/concourse/deploy.yml

resources:
- name: source-code
  type: git
  source:
    uri: https://github.com/echosoft-consultancy/echo.git
